Completed issue-2-view-their-entries
SeungjooKimSJ/code-journal pull request #6
Opened 2021-04-05 07:55 UTC by SeungjooKimSJ

![image](https://user-images.githubusercontent.com/68725614/113551511-a24e8a80-95a9-11eb-94b2-fa8460b84419.png)
![image](https://user-images.githubusercontent.com/68725614/113551528-a8dd0200-95a9-11eb-8ac6-7872d245bc47.png)

2021-04-05 20:00 UTC, codingcodymiller requested changes

2021-04-05 20:00 UTC, codingcodymiller commented on css/styles.css
> +}
This already exists in `layout.css`, it can be removed.

2021-04-05 20:00 UTC, codingcodymiller commented on js/main.js
> +  location.reload();
You should _**never**_ use `location.reload`. It completely refreshes and rebuilds the page, which is extremely inefficient. Why are you doing this?

2021-06-17 19:45 UTC, thebearingedge approved these changes

2021-06-17 19:54 UTC, merged